src/coming_soon/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.ContactUsView.as_view(), name='coming-soon'),
]

src/coming_soon/models.py
from django.db import models


class PrelaunchSignUp(models.Model):
    """Prelaunch SignUp model."""
    name = models.CharField(max_length=255)
    email = models.EmailField()
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "{} ({}) signed-up on {}".format(self.name, self.email, self.created)

src/coming_soon/forms.py
from django.forms import ModelForm

from .models import PrelaunchSignUp


class ContactUsForm(ModelForm):
    """
    PreLaunch Contact Us Form.
    """
    class Meta:
        model = PrelaunchSignUp
        fields = ['name', 'email']

src/coming_soon/views.py
from django.views.generic import FormView
from django.contrib import messages
from django.core.mail import EmailMessage
from django.conf import settings
from django.urls import reverse_lazy

from .forms import ContactUsForm
from .models import PrelaunchSignUp


class ContactUsView(FormView):

    template_name = 'contact.html'
    form_class = ContactUsForm
    success_url = reverse_lazy('coming-soon')

    @staticmethod
    def send_user_email(user_email):
        msg = EmailMessage(
            subject='Thank you for contacting us!',
            body='Thank you for contacting us You will be notified once the product goes live.',
            from_email=getattr(settings, 'PRELAUNCH_EMAIL', 'None'),
            to=[user_email, ]
        )
        msg.send()

    @staticmethod
    def create_user(user_data):
        PrelaunchSignUp.objects.create(name=user_data['name'], email=user_data['email'])

    def post(self, request, *args, **kwargs):

        form = self.get_form()
        if form.is_valid():
            user_data = request.POST
            self.create_user(user_data)
            self.send_user_email(user_email=user_data['email'])
            messages.success(request, 'Your details were captured successfully.')
        return super(ContactUsView, self).post(request)

src/coming_soon/templates/contact.html
<!DOCTYPE html>
<html>
<head>
    <title>Coming Soon</title>
    <!-- UIkit CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.0.0-beta.30/css/uikit.min.css" />
    {% load staticfiles %}
</head>

<body style="background-image: url({% static "coming_soon/images/forestbridge.jpg" %}); background-repeat: no-repeat;background-size: cover;">
    <div style="" class="uk-grid-divider uk-child-width-expand@s uk-margin-large-top">
        <div style="margin: 0 auto;" class="uk-card uk-card-default uk-card-body uk-width-1-2@m">
            <form class="uk-form-horizontal uk-margin-medium" method="post">{% csrf_token %}
                <div class="uk-margin">
                    <label class="uk-form-label" for="id_name">Name:</label>
                    <div class="uk-form-controls">
                        <input class="uk-input uk-form-width-large" id="id_name" name="name" type="text" placeholder="Enter you name." required>
                    </div>
                </div>
                <div class="uk-margin">
                    <label class="uk-form-label" for="id_email">Email:</label>
                    <div class="uk-form-controls">
                        <input class="uk-input uk-form-width-large" id="id_email" name="email" type="email" placeholder="Enter your email." required>
                    </div>
                </div>
                <button style="float: right;" class="uk-button uk-button-default">Submit</button>
            </form>
            {% if messages %}
            <ul style="padding: 0; margin: 0;" class="messages">
                {% for message in messages %}
                <span {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</span>
                {% endfor %}
            </ul>
            {% endif %}
        </div>
    </div>
    <!-- jQuery is required -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <!-- UIkit JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.0.0-beta.30/js/uikit.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.0.0-beta.30/js/uikit-icons.min.js"></script>
</body>

</html>